"""Build paper-ready tables directly from the logged *_metrics.json files:

  1. Accuracy (Table 1 layout): one row per method, avg incremental accuracy
     (A-bar) + final accuracy (A_T) per dataset, mean +/- std over seeds.
  2. Efficiency (Figure 4a layout): one row per method, key cost metrics
     averaged across all six datasets -- train time, eval latency, inference
     FLOPs/sample, peak training memory, params.

Reuses aggregate_results.py's log-scanning/mean-std logic for both.

Outputs:
    results/paper_table.csv          accuracy, wide CSV
    results/paper_table.tex          accuracy, ready-to-paste LaTeX
    results/efficiency_table.csv     efficiency, wide CSV
    results/efficiency_table.tex     efficiency, ready-to-paste LaTeX

Usage:
    python make_paper_table.py --roots logs ../pilot_baselines/logs
"""
import argparse
import csv
import os

import numpy as np

from aggregate_results import aggregate, load_runs

# Internal dataset key -> paper-style column header.
DATASETS = [
    ("cifar224", "CIFAR B0 Inc5"),
    ("cub", "CUB B0 Inc10"),
    ("imagenetr", "IN-R B0 Inc20"),
    ("imageneta", "IN-A B0 Inc20"),
    ("omnibenchmark", "OmniBench B0 Inc30"),
    ("vtab", "VTAB B0 Inc10"),
]

# Internal model_name -> (paper-style display name, sort order).
METHODS = [
    ("simplecil", "SimpleCIL"),
    ("ranpac", "RanPAC"),
    ("l2p", "L2P"),
    ("dualprompt", "DualPrompt"),
    ("coda_prompt", "CODAPrompt"),
    ("aper_adapter", "APER-Adapter"),
    ("ease", "EASE"),
    ("mos", "MOS"),
    ("tosca", "TOSCA (ours)"),
]


def build_table(rows):
    """-> {method_key: {dataset_key: {"abar_mean","abar_std","at_mean","at_std","seeds"}}}"""
    by_key = {(r["model"], r["dataset"]): r for r in rows}
    table = {}
    for model_key, _ in METHODS:
        table[model_key] = {}
        for ds_key, _ in DATASETS:
            r = by_key.get((model_key, ds_key))
            if r is None:
                table[model_key][ds_key] = None
                continue
            table[model_key][ds_key] = {
                "abar_mean": r["avg_inc_acc_mean"],
                "abar_std": r["avg_inc_acc_std"],
                "at_mean": r["final_top1_mean"],
                "at_std": r["final_top1_std"],
                "seeds": r["seeds"],
                "seeds_partial": r["seeds_partial"],
            }
    return table


def write_csv(table, path):
    header = ["method"]
    for _, ds_label in DATASETS:
        header += [f"{ds_label} Abar_mean", f"{ds_label} Abar_std",
                   f"{ds_label} AT_mean", f"{ds_label} AT_std", f"{ds_label} seeds"]
    with open(path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(header)
        for model_key, model_label in METHODS:
            row = [model_label]
            for ds_key, _ in DATASETS:
                cell = table[model_key][ds_key]
                if cell is None:
                    row += ["", "", "", "", 0]
                else:
                    row += [cell["abar_mean"], cell["abar_std"],
                            cell["at_mean"], cell["at_std"], cell["seeds"]]
            writer.writerow(row)
    print(f"wrote {path}")


def fmt_cell(mean, std, bold):
    if mean is None:
        return "-"
    s = f"{mean:.2f}" + (f" \\pm {std:.2f}" if std is not None else "")
    return f"\\textbf{{{s}}}" if bold else s


def write_latex(table, path):
    # best (max) per column, ignoring None -- ties all get bolded.
    best = {}
    for ds_key, _ in DATASETS:
        for metric in ("abar_mean", "at_mean"):
            vals = [
                table[m][ds_key][metric]
                for m, _ in METHODS
                if table[m].get(ds_key) and table[m][ds_key][metric] is not None
            ]
            best[(ds_key, metric)] = max(vals) if vals else None

    lines = []
    lines.append("% Auto-generated by make_paper_table.py -- do not hand-edit, regenerate instead.")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\resizebox{\\textwidth}{!}{%")
    lines.append("\\begin{tabular}{l" + "cc" * len(DATASETS) + "}")
    lines.append("\\toprule")

    header1 = ["Method"] + [
        f"\\multicolumn{{2}}{{c}}{{{ds_label}}}" for _, ds_label in DATASETS
    ]
    lines.append(" & ".join(header1) + " \\\\")
    cmids = " ".join(
        f"\\cmidrule(lr){{{2 + 2*i}-{3 + 2*i}}}" for i in range(len(DATASETS))
    )
    lines.append(cmids)
    header2 = [""] + [
        h for _ in DATASETS for h in ("$\\bar{A}$", "$A_T$")
    ]
    lines.append(" & ".join(header2) + " \\\\")
    lines.append("\\midrule")

    for model_key, model_label in METHODS:
        cells = [model_label]
        for ds_key, _ in DATASETS:
            cell = table[model_key][ds_key]
            if cell is None:
                cells += ["-", "-"]
                continue
            cells.append(fmt_cell(
                cell["abar_mean"], cell["abar_std"],
                bold=cell["abar_mean"] == best[(ds_key, "abar_mean")],
            ))
            cells.append(fmt_cell(
                cell["at_mean"], cell["at_std"],
                bold=cell["at_mean"] == best[(ds_key, "at_mean")],
            ))
        row_line = " & ".join(cells) + " \\\\"
        if model_label == "TOSCA (ours)":
            lines.append("\\midrule")
        lines.append(row_line)

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}%")
    lines.append("}")
    lines.append(
        "\\caption{Average accuracy ($\\bar{A}$) and last accuracy ($A_T$) "
        "on six datasets with ViT-B/16-IN21K, mean $\\pm$ std over 5 seeds.}"
    )
    lines.append("\\label{tab:main-results}")
    lines.append("\\end{table}")

    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {path}")


# Per-dataset efficiency metric -> paper-style column header + unit.
EFF_METRICS = [
    ("train_seconds_total", "Train Time (min)", 1.0 / 60.0),
    ("eval_ms_per_sample", "Eval (ms/smp)", 1.0),
    ("inference_gflops_per_sample", "Inference (GFLOPs)", 1.0),
    ("train_gflops_est", "Train (GFLOPs, est.)", 1.0),
    ("train_peak_mem_mb", "Peak Train Mem (MB)", 1.0),
    ("total_params_m", "Params (M)", 1.0),
    ("trainable_params_m", "Trainable Params (M)", 1.0),
]


def build_efficiency_table(rows):
    """One row per method: each metric averaged across whatever datasets have
    data (equal weight per dataset, not per seed -- a dataset with fewer
    completed seeds doesn't get proportionally more influence)."""
    by_key = {(r["model"], r["dataset"]): r for r in rows}
    table = {}
    for model_key, _ in METHODS:
        per_metric = {}
        n_datasets = 0
        for ds_key, _ in DATASETS:
            r = by_key.get((model_key, ds_key))
            if r is None:
                continue
            n_datasets += 1
            for metric, _, _ in EFF_METRICS:
                mean = r.get(f"{metric}_mean")
                if mean is not None:
                    per_metric.setdefault(metric, []).append(mean)
        table[model_key] = {
            "n_datasets": n_datasets,
            **{
                metric: (float(np.mean(vals)), float(np.std(vals))) if vals else (None, None)
                for metric, vals in (
                    (m, per_metric.get(m, [])) for m, _, _ in EFF_METRICS
                )
            },
        }
    return table


def write_efficiency_csv(table, path):
    header = ["method", "n_datasets"] + [
        f"{label}_mean" if i % 2 == 0 else f"{label}_std"
        for _, label, _ in EFF_METRICS
        for i in range(2)
    ]
    with open(path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(header)
        for model_key, model_label in METHODS:
            row = table[model_key]
            line = [model_label, row["n_datasets"]]
            for metric, _, scale in EFF_METRICS:
                mean, std = row[metric]
                line.append(mean * scale if mean is not None else "")
                line.append(std * scale if std is not None else "")
            writer.writerow(line)
    print(f"wrote {path}")


def write_efficiency_latex(table, path):
    # best = LOWEST cost per column (efficiency, not accuracy) -- ignore
    # params columns for bolding, since "best" isn't well-defined there.
    cost_metrics = {"train_seconds_total", "eval_ms_per_sample",
                     "inference_gflops_per_sample", "train_gflops_est",
                     "train_peak_mem_mb"}
    best = {}
    for metric, _, _ in EFF_METRICS:
        if metric not in cost_metrics:
            continue
        vals = [
            table[m][metric][0] for m, _ in METHODS
            if table[m][metric][0] is not None
        ]
        best[metric] = min(vals) if vals else None

    lines = []
    lines.append("% Auto-generated by make_paper_table.py -- do not hand-edit, regenerate instead.")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\resizebox{\\textwidth}{!}{%")
    lines.append("\\begin{tabular}{l" + "c" * len(EFF_METRICS) + "}")
    lines.append("\\toprule")
    lines.append("Method & " + " & ".join(label for _, label, _ in EFF_METRICS) + " \\\\")
    lines.append("\\midrule")

    for model_key, model_label in METHODS:
        row = table[model_key]
        cells = [model_label]
        for metric, _, scale in EFF_METRICS:
            mean, std = row[metric]
            if mean is None:
                cells.append("-")
                continue
            s = f"{mean * scale:.2f} \\pm {std * scale:.2f}" if std is not None else f"{mean * scale:.2f}"
            if metric in cost_metrics and best.get(metric) is not None and mean == best[metric]:
                s = f"\\textbf{{{s}}}"
            cells.append(s)
        row_line = " & ".join(cells) + " \\\\"
        if model_label == "TOSCA (ours)":
            lines.append("\\midrule")
        lines.append(row_line)

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}%")
    lines.append("}")
    lines.append(
        "\\caption{Efficiency comparison, mean $\\pm$ std across all six "
        "datasets (each dataset weighted equally). Lowest cost per column "
        "in bold.}"
    )
    lines.append("\\label{tab:efficiency}")
    lines.append("\\end{table}")

    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {path}")


def build_taskwise_table(runs, dataset_key):
    """-> ({method_key: {task_idx: (mean, std, n_seeds)}}, n_tasks)
    Per-task CNN top1 (the raw curve, not the running average), mean/std
    across whatever seeds have that task recorded for this dataset."""
    n_tasks = 0
    per_method = {}
    for model_key, _ in METHODS:
        by_task = {}
        for run in runs.get((model_key, dataset_key), {}).values():
            for t in run["tasks"]:
                idx, top1 = t.get("task"), t.get("cnn_top1")
                if idx is None or top1 is None:
                    continue
                by_task.setdefault(idx, []).append(top1)
        n_tasks = max(n_tasks, (max(by_task) + 1) if by_task else 0)
        per_method[model_key] = {
            idx: (float(np.mean(vals)), float(np.std(vals)), len(vals))
            for idx, vals in by_task.items()
        }
    return per_method, n_tasks


def write_taskwise_csv(table, n_tasks, path):
    header = ["method"] + [f"T{t+1}_mean" for t in range(n_tasks)] + \
             [f"T{t+1}_std" for t in range(n_tasks)] + \
             [f"T{t+1}_seeds" for t in range(n_tasks)] + ["Avg_mean", "Avg_std"]
    with open(path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(header)
        for model_key, model_label in METHODS:
            row_data = table[model_key]
            means = [row_data[t][0] if t in row_data else "" for t in range(n_tasks)]
            stds = [row_data[t][1] if t in row_data else "" for t in range(n_tasks)]
            seeds = [row_data[t][2] if t in row_data else 0 for t in range(n_tasks)]
            all_means = [row_data[t][0] for t in range(n_tasks) if t in row_data]
            avg_mean = float(np.mean(all_means)) if all_means else ""
            avg_std = float(np.std(all_means)) if all_means else ""
            writer.writerow([model_label] + means + stds + seeds + [avg_mean, avg_std])
    print(f"wrote {path}")


def write_taskwise_latex(table, n_tasks, ds_label, path):
    best_per_task = {}
    for t in range(n_tasks):
        vals = [table[m][t][0] for m, _ in METHODS if t in table[m]]
        best_per_task[t] = max(vals) if vals else None
    avg_by_method = {}
    for model_key, _ in METHODS:
        all_means = [table[model_key][t][0] for t in range(n_tasks) if t in table[model_key]]
        avg_by_method[model_key] = float(np.mean(all_means)) if all_means else None
    best_avg = max((v for v in avg_by_method.values() if v is not None), default=None)

    lines = []
    lines.append("% Auto-generated by make_paper_table.py -- do not hand-edit, regenerate instead.")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\resizebox{\\textwidth}{!}{%")
    lines.append("\\begin{tabular}{l" + "c" * n_tasks + "c}")
    lines.append("\\toprule")
    lines.append(
        "Task & " + " & ".join(f"T{t+1}" for t in range(n_tasks)) + " & Avg \\\\"
    )
    lines.append("\\midrule")

    for model_key, model_label in METHODS:
        cells = [model_label]
        for t in range(n_tasks):
            if t not in table[model_key]:
                cells.append("-")
                continue
            mean, _, _ = table[model_key][t]
            s = f"{mean:.1f}"
            if best_per_task[t] is not None and mean == best_per_task[t]:
                s = f"\\textbf{{{s}}}"
            cells.append(s)
        avg = avg_by_method[model_key]
        if avg is None:
            cells.append("-")
        else:
            s = f"{avg:.1f}"
            cells.append(f"\\textbf{{{s}}}" if avg == best_avg else s)
        row_line = " & ".join(cells) + " \\\\"
        if model_label == "TOSCA (ours)":
            lines.append("\\midrule")
        lines.append(row_line)

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}%")
    lines.append("}")
    lines.append(
        f"\\caption{{Task-wise accuracy ($A_t$) on {ds_label} with ViT-B/16-IN21K, "
        "mean over 5 seeds.}"
    )
    lines.append(f"\\label{{tab:taskwise-{ds_label.split()[0].lower()}}}")
    lines.append("\\end{table}")

    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {path}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--roots", nargs="+", default=["logs", "../pilot_baselines/logs"],
        help="log roots to scan for *_metrics.json",
    )
    parser.add_argument("--out", type=str, default="results")
    cli = parser.parse_args()

    runs = load_runs([r for r in cli.roots if os.path.isdir(r)])
    if not runs:
        print("No *_metrics.json found under: " + ", ".join(cli.roots))
        return
    rows = aggregate(runs)
    table = build_table(rows)
    os.makedirs(cli.out, exist_ok=True)
    write_csv(table, os.path.join(cli.out, "paper_table.csv"))
    write_latex(table, os.path.join(cli.out, "paper_table.tex"))

    eff_table = build_efficiency_table(rows)
    write_efficiency_csv(eff_table, os.path.join(cli.out, "efficiency_table.csv"))
    write_efficiency_latex(eff_table, os.path.join(cli.out, "efficiency_table.tex"))

    # Task-wise curve (paper's Table 2 layout), one file per dataset.
    for ds_key, ds_label in DATASETS:
        tw_table, n_tasks = build_taskwise_table(runs, ds_key)
        if n_tasks == 0:
            continue
        write_taskwise_csv(tw_table, n_tasks, os.path.join(cli.out, f"taskwise_{ds_key}.csv"))
        write_taskwise_latex(tw_table, n_tasks, ds_label, os.path.join(cli.out, f"taskwise_{ds_key}.tex"))

    # Flag anything short of 5 seeds so partial waves don't sneak into the paper.
    incomplete = []
    for model_key, model_label in METHODS:
        for ds_key, ds_label in DATASETS:
            cell = table[model_key][ds_key]
            if cell is None:
                incomplete.append(f"{model_label} / {ds_label}: NO DATA")
            elif cell["seeds"] < 5:
                incomplete.append(
                    f"{model_label} / {ds_label}: only {cell['seeds']}/5 seeds"
                    + (f" ({cell['seeds_partial']} partial runs excluded)" if cell["seeds_partial"] else "")
                )
    if incomplete:
        print(f"\n{len(incomplete)} cell(s) not yet at full 5 seeds:")
        for line in incomplete:
            print(f"  {line}")


if __name__ == "__main__":
    main()
